1. Cria tabela cliente
CREATE TABLE cliente (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
   nome VARCHAR(100),
   email VARCHAR(100)
);

2. Insere o primeiro cliente
insert into cliente (nome, email) values ('João da Silva', 'jojo@gmail.com');

3. Insere o segundo cliente
insert into cliente (nome, email) values ('Sergio Fonseca', 'sergio@bol.com');

4. Lista todos os clientes
select * from cliente